name = "gello-docs"
compatibility_date = "2024-12-29"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

routes = [
  { pattern = "gello.net/*", zone_name = "gello.net" },
  { pattern = "www.gello.net/*", zone_name = "gello.net" }
]

[observability]
enabled = true
